# Site settings
title: Nile Imtiaz
email: nile.imtiaz01@gmail.com
description: > # keep this and put description below
  Game Design + Development // UI + Graphic Design // Character Concept Art 
url: "https://nile-imtiaz.github.io/portfolio/" # the base hostname & protocol for your site
linkedin_url: "https://www.linkedin.com/in/nile-imtiaz/"
itchio_url: "https://ariverinegypt.itch.io/"
footer_text: "This site uses <a href='https://github.com/gamingportfolio/urban-theme-portfolio'>urban-theme (portfolio)</a>."

# Build settings
markdown: kramdown
permalink: pretty
